
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 55
#define YY_END_OF_BUFFER 56
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[366] =
    {   0,
        0,    0,   56,   55,   54,   53,   55,   55,    2,    7,
       51,   51,    1,    5,    6,   55,   55,    3,    4,    0,
       50,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   51,    0,
        0,   51,    0,    0,    0,   50,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   51,   52,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   22,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   49,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    8,   19,    0,
        0,    0,    0,    0,    0,   47,   39,    0,    0,    0,
        0,    0,    0,    0,   34,    0,    0,   20,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   46,   27,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    9,   17,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   11,
        0,   10,    0,    0,    0,    0,    0,   48,    0,    0,
        0,    0,   13,    0,    0,    0,    0,   33,    0,    0,
        0,    0,   32,   35,    0,    0,    0,    0,    0,    0,
        0,    0,   26,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   24,    0,    0,    0,    0,    0,    0,
       23,    0,   12,   29,    0,    0,    0,    0,    0,    0,
       41,    0,    0,    0,    0,    0,   45,    0,    0,   40,

        0,   14,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   44,    0,   42,    0,    0,    0,
        0,    0,    0,   36,   15,    0,    0,    0,   25,    0,
        0,    0,   16,    0,    0,    0,    0,   28,    0,   43,
        0,    0,    0,    0,    0,    0,    0,    0,   37,    0,
        0,    0,    0,    0,    0,   18,    0,    0,   21,   31,
        0,   38,    0,   30,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    6,    7,    8,    1,    9,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   11,    1,    1,
        1,    1,    1,    1,    1,   12,   13,   14,   15,    1,
        1,   16,   17,    1,    1,    1,    1,   18,   19,   20,
        1,    1,   21,   22,    1,    1,    1,    1,    1,    1,
       23,   24,   25,    1,    1,    1,   26,   27,   28,   29,

       30,   31,   32,    1,   33,   34,   35,   36,   37,   38,
       39,   40,    1,   41,   42,   43,   44,   45,   46,   47,
       48,   49,   50,    1,   51,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[52] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[369] =
    {   0,
        0,   50,  118, 1026, 1026, 1026,   98,  105, 1026, 1026,
        4,    7, 1026, 1026, 1026,   88,   71, 1026, 1026,    4,
     1026,   15,   34,   25,   41,   44,   62,   16,   65,   20,
       66,   74,   79,   80,  109,  115,   84,  133,   12,   17,
       24,   27,   51,   38,   87,   92,  143,  141,  145,  146,
      147,  149,  152,  154,  156,  158,  157,  164,  173,  182,
      185,  189,  190,  192,  197,  200,  214,  203,  198,  204,
      216,  221,  222,  227,   96,  100,   37,   42,  225,  237,
      238,  240,  244,  251,  253,  256,  262,  263,  265,  267,
      268,  270,  272,  274, 1026,  279,  281,  291,  297,  302,

      303,  305,  309,  306,  318,  307,  319,  321,  320,  337,
      332,   17, 1026,  345,  347,  348,  349,  350,  351,  356,
      364,  372,  353,  374,  355,  387,  393,  396,  397,  399,
      402,  403,  404,  406,  408,  409,  414,  425,  427,  430,
      437,  441,  442,  443,  446,  444,  449,  448,  452,  459,
      456,  458,  460,  467,  477,  482,  485,  486,  488,  490,
      489,  496,  499,  503,  500,  504,  507, 1026, 1026,  513,
      517,  526,  529,  531,  532, 1026, 1026,  534,  548,  535,
      541,  536,  550,  557, 1026,  560,  562, 1026,  565,  566,
      574,  575,  576,  578,  583,  588,  587,  589, 1026, 1026,

      590,  592,  606,  599,  611,  616,  620,  621,  623,  627,
      629,  632,  633,  648,  634,  637,  639,  642, 1026, 1026,
      651,  660,  661,  663,  667,  672,  669,  674,  675, 1026,
      679, 1026,  682,  678,  686,  691,  690, 1026,  703,  712,
      714,  716, 1026,  717,  718,  719,  720, 1026,  724,  731,
      727,  748, 1026, 1026,  729,  750,  752,  754,  757,  758,
      759,  761, 1026,  765,  769,  762,  775,  767,  776,  780,
      786,  783,  790, 1026,  797,  798,  802,  804,  807,  808,
     1026,  811, 1026, 1026,  815,  816,  819,  820,  823,  825,
     1026,  830,  838,  844,  849,  847, 1026,  851,  855, 1026,

      857, 1026,  859,  861,  863,  865,  868,  870,  873,  872,
      874,  884,  889,  895, 1026,  896, 1026,  898,  899,  903,
      908,  910,  911, 1026, 1026,  913,  914,  917, 1026,  924,
      925,  929, 1026,  938,  926,  939,  941, 1026,  942, 1026,
      943,  954,  951,  966,  956,  969,  972,  975, 1026,  979,
      973,  981,  983,  982,  984, 1026,  988,  985, 1026, 1026,
      987, 1026,  996, 1026, 1026,   40,   29,    0
    } ;

static const flex_int16_t yy_def[369] =
    {   0,
      366,  366,  365,  365,  365,  365,  367,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  367,
      365,  368,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  365,  365,
      365,  365,  365,  365,  367,  367,  368,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  365,  365,  365,  365,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  365,  367,  367,  367,  367,  367,

      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  365,  365,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  365,  365,  367,
      367,  367,  367,  367,  367,  365,  365,  367,  367,  367,
      367,  367,  367,  367,  365,  367,  367,  365,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  365,  365,

      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  365,  365,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  365,
      367,  365,  367,  367,  367,  367,  367,  365,  367,  367,
      367,  367,  365,  367,  367,  367,  367,  365,  367,  367,
      367,  367,  365,  365,  367,  367,  367,  367,  367,  367,
      367,  367,  365,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  365,  367,  367,  367,  367,  367,  367,
      365,  367,  365,  365,  367,  367,  367,  367,  367,  367,
      365,  367,  367,  367,  367,  367,  365,  367,  367,  365,

      367,  365,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  365,  367,  365,  367,  367,  367,
      367,  367,  367,  365,  365,  367,  367,  367,  365,  367,
      367,  367,  365,  367,  367,  367,  367,  365,  367,  365,
      367,  367,  367,  367,  367,  367,  367,  367,  365,  367,
      367,  367,  367,  367,  367,  365,  367,  367,  365,  365,
      367,  365,  367,  365,    0,  365,  365,  365
    } ;

static const flex_int16_t yy_nxt[1078] =
    {   0,
       45,    5,    6,    7,    8,    9,   10,   21,   11,   12,
       13,   40,   41,   41,   40,   42,   42,   20,   46,   21,
       75,   75,   14,   21,   15,   76,   76,   22,   21,   20,
       16,   40,   41,   41,   40,   42,   42,   21,   47,   22,
        4,   59,   17,   22,   21,   62,  113,   21,   22,   18,
       19,    5,    6,    7,    8,    9,   10,   22,   11,   12,
       13,   48,   49,   52,   22,   21,   53,   22,   21,   21,
       50,  113,   14,   55,   15,   51,   56,   21,  112,   54,
       16,   78,   21,   21,   57,   22,   77,   21,   22,   22,
       21,   63,   17,   60,   58,   21,   61,   22,   64,   18,

       19,   21,   22,   22,   75,   75,   65,   22,   76,   76,
       22,   44,   21,   43,   39,   22,   72,  365,   21,  365,
       67,   22,   66,   23,   24,   25,   26,  365,   27,   28,
       29,   30,   22,   31,   32,   33,   21,   34,   22,   35,
       36,   68,   37,   38,   21,   20,   46,   69,   21,   21,
       21,   70,   21,   71,  365,   21,   22,   21,   73,   21,
       21,   21,  365,  365,   22,   74,   47,   21,   22,   22,
       22,  365,   22,   80,   82,   22,   21,   22,  365,   22,
       22,   22,   91,   79,   81,   95,   83,   22,   21,   85,
      365,   86,   21,   21,   84,   21,   22,   87,   88,   89,

       21,   21,   90,   21,   92,   22,   21,   21,   22,   94,
       93,  365,   22,   22,  365,   22,   97,   21,  365,   21,
       22,   22,   96,   22,   21,   21,   22,   22,   21,  107,
       21,   98,  365,   99,  100,  101,  102,   22,  106,   22,
       21,   21,  365,   21,   22,   22,  103,   21,   22,  365,
       22,  105,  104,  110,   21,  115,   21,  114,  108,   21,
       22,   22,  109,   22,  111,   21,   21,   22,   21,  117,
       21,   21,  365,   21,   22,   21,   22,   21,  365,   22,
      119,  116,   21,  365,   21,   22,   22,  118,   22,  122,
       22,   22,  123,   22,   21,   22,  120,   22,  121,  125,

       21,  128,   22,  129,   22,   21,   21,  124,   21,   21,
       21,  127,   21,  126,   22,  131,  365,  130,  365,  365,
       22,   21,   21,   21,   21,   22,   22,  365,   22,   22,
       22,  136,   22,  132,  134,   21,  137,  365,  135,  133,
       21,   22,   22,   22,   22,  139,  143,  140,   21,  141,
       21,   21,   21,   21,   21,   22,   21,  138,   21,   21,
       22,  142,  365,  144,  365,  365,  145,   21,   22,  146,
       22,   22,   22,   22,   22,   21,   22,   21,   22,   22,
      156,  365,  152,  158,  148,  149,  150,   22,  365,  147,
       21,  151,  153,  154,  365,   22,   21,   22,  159,   21,

       21,  155,   21,  160,  365,   21,  168,  169,  161,   21,
       22,   21,   21,  164,  157,  365,   22,   21,  165,   22,
       22,  365,   22,  171,  163,   22,   22,   22,   21,   22,
       21,   22,   22,  176,  365,  162,  365,   22,  172,  166,
      177,  167,  170,  173,   21,   21,   21,   21,   22,   21,
       22,  185,   21,   22,  174,   21,  175,  365,  365,  188,
       22,   21,   21,   21,   22,   22,   22,   22,  180,   22,
       21,   22,   22,  182,  365,   22,  183,  179,  184,   22,
       21,   22,   22,   22,  178,   21,  181,  187,   21,   21,
       22,   21,   21,   21,  186,  365,  189,  190,  365,  199,

       22,  365,  200,   21,  191,   22,   21,   21,   22,   22,
       21,   22,   22,   22,  192,  195,   21,  194,  197,   22,
       21,  198,   22,   22,  193,  365,   22,   22,  196,   21,
       22,  201,   21,  203,   21,   21,   22,   21,   21,   21,
       22,  365,  206,  209,   21,  204,  365,  202,  208,   22,
      365,   21,   22,   21,   22,   22,  205,   22,   22,   22,
      219,  215,  212,  220,   22,   21,  207,  213,   21,   21,
      214,   22,  210,   22,  365,  211,  217,   21,   21,   21,
       22,   21,  216,   22,  365,   22,   21,  218,   22,   22,
      230,   21,   21,  232,  221,   21,  365,   22,   22,   22,

      365,   22,   21,  225,  227,  222,   22,  223,  226,   21,
       22,   22,   22,   22,   21,   22,  224,  229,  234,   21,
      228,  365,   22,  238,   21,  231,   21,  365,  365,   22,
       21,  233,  243,  365,   22,   21,   21,   21,  239,   22,
      248,  235,   21,   22,   22,   21,   22,  236,  241,  365,
       22,   21,   22,  237,   21,   22,   22,   22,  245,  240,
       22,  246,   22,   21,  253,   22,  254,  244,  365,  242,
       21,   22,   21,  250,   22,   21,  247,   21,   21,  365,
      249,   21,   21,   22,   22,   21,   22,  365,  251,  263,
       22,  365,   22,   21,   21,   22,  365,   22,   22,  255,

      259,   22,   22,  262,  264,   22,   21,  252,  260,   22,
      256,  261,  257,   22,   22,   21,  258,   21,  265,   21,
       21,   21,   21,   21,  365,  365,   22,  274,  365,  365,
       21,  365,   21,  266,   21,   22,  365,   22,  365,   22,
       22,   22,   22,   22,  267,  273,  270,   22,  275,  271,
       22,   21,   22,   21,   22,   21,  268,  281,  276,  272,
       21,  283,  284,  269,   21,   21,  278,  365,   21,  277,
       21,   22,   21,   22,  365,   22,  288,   22,   21,  291,
       22,   22,   22,   21,   22,   22,   21,  279,   22,   21,
       22,  282,   22,   21,  280,  365,  290,  286,   22,   22,

       21,  297,  285,   22,  287,   21,   22,   21,  294,   22,
      300,   21,  289,   22,  302,  293,  292,  365,   21,   21,
       22,   22,   21,   21,  365,   22,   21,   22,   21,  365,
       22,   22,  295,   21,   22,  299,  365,  301,   22,   22,
      296,   21,   22,   22,  303,  365,   22,   21,   22,  298,
       21,  305,   21,   22,   21,  306,  308,  304,  315,  309,
       21,   22,  317,  365,   21,  307,   21,   22,   21,  365,
       22,   21,   22,   21,   22,  324,   21,  325,   22,  310,
       22,  312,   22,  313,   22,  316,   22,   21,   22,  311,
      314,   22,   21,   22,  320,   22,   22,   22,   21,  329,

      319,   21,   21,  318,  365,  365,   21,   22,  322,  321,
      323,  333,   22,   21,   21,  327,   21,   21,   22,   22,
      338,   22,   22,  365,  328,  326,   22,   21,  340,   21,
      331,   22,   21,   22,   22,  365,   22,   22,  330,  332,
       22,   21,   21,  337,   21,   21,   21,   22,   22,   22,
      334,  365,   22,  335,  349,  336,  339,   21,  341,   21,
      365,   22,   22,  365,   22,   22,   22,  343,  346,   21,
      342,  344,   21,  365,   22,   21,  356,   22,   21,   22,
      347,  345,   21,  348,   21,  359,   21,  360,  362,   22,
       21,   21,   22,  350,  365,   22,   22,  351,   22,  364,

      365,  365,   22,  365,   22,   22,   22,   22,   22,  365,
       22,   22,  352,  365,  353,  363,  354,  361,  365,   22,
      355,  365,  365,  357,  358,    3,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365
    } ;

static const flex_int16_t yy_chk[1078] =
    {   0,
      368,    1,    1,    1,    1,    1,    1,   20,    1,    1,
        1,   11,   11,   11,   12,   12,   12,   22,   22,   28,
       39,   39,    1,   30,    1,   40,   40,   20,   24,  367,
        1,   41,   41,   41,   42,   42,   42,   23,   22,   28,
      366,   28,    1,   30,   25,   30,  112,   26,   24,    1,
        1,    2,    2,    2,    2,    2,    2,   23,    2,    2,
        2,   23,   23,   24,   25,   27,   25,   26,   29,   31,
       23,   78,    2,   26,    2,   23,   26,   32,   77,   25,
        2,   44,   33,   34,   26,   27,   43,   37,   29,   31,
       45,   31,    2,   29,   27,   46,   29,   32,   31,    2,

        2,    7,   33,   34,   75,   75,   32,   37,   76,   76,
       45,   17,   35,   16,    8,   46,   37,    3,   36,    0,
       34,    7,   33,    7,    7,    7,    7,    0,    7,    7,
        7,    7,   35,    7,    7,    7,   38,    7,   36,    7,
        7,   35,    7,    7,   48,   47,   47,   35,   49,   50,
       51,   35,   52,   36,    0,   53,   38,   54,   38,   55,
       57,   56,    0,    0,   48,   38,   47,   58,   49,   50,
       51,    0,   52,   49,   51,   53,   59,   54,    0,   55,
       57,   56,   57,   48,   50,   60,   52,   58,   61,   54,
        0,   54,   62,   63,   53,   64,   59,   55,   56,   56,

       65,   69,   56,   66,   58,   60,   68,   70,   61,   59,
       58,    0,   62,   63,    0,   64,   62,   67,    0,   71,
       65,   69,   61,   66,   72,   73,   68,   70,   79,   70,
       74,   63,    0,   64,   65,   66,   66,   67,   69,   71,
       80,   81,    0,   82,   72,   73,   67,   83,   79,    0,
       74,   68,   67,   73,   84,   80,   85,   79,   71,   86,
       80,   81,   72,   82,   74,   87,   88,   83,   89,   82,
       90,   91,    0,   92,   84,   93,   85,   94,    0,   86,
       84,   81,   96,    0,   97,   87,   88,   83,   89,   87,
       90,   91,   88,   92,   98,   93,   85,   94,   86,   90,

       99,   93,   96,   94,   97,  100,  101,   89,  102,  104,
      106,   92,  103,   91,   98,   97,    0,   96,    0,    0,
       99,  105,  107,  109,  108,  100,  101,    0,  102,  104,
      106,  102,  103,   98,  100,  111,  103,    0,  101,   99,
      110,  105,  107,  109,  108,  104,  108,  105,  114,  106,
      115,  116,  117,  118,  119,  111,  123,  103,  125,  120,
      110,  107,    0,  109,    0,    0,  110,  121,  114,  111,
      115,  116,  117,  118,  119,  122,  123,  124,  125,  120,
      123,    0,  119,  125,  115,  116,  117,  121,    0,  114,
      126,  118,  120,  121,    0,  122,  127,  124,  126,  128,

      129,  122,  130,  126,    0,  131,  132,  133,  126,  134,
      126,  135,  136,  129,  124,    0,  127,  137,  129,  128,
      129,    0,  130,  135,  128,  131,  132,  133,  138,  134,
      139,  135,  136,  140,    0,  127,    0,  137,  136,  130,
      141,  131,  134,  137,  142,  143,  144,  146,  138,  145,
      139,  148,  147,  140,  138,  149,  139,    0,    0,  151,
      141,  152,  150,  153,  142,  143,  144,  146,  144,  145,
      154,  148,  147,  146,    0,  149,  146,  143,  147,  151,
      155,  152,  150,  153,  142,  156,  145,  150,  157,  158,
      154,  159,  161,  160,  149,    0,  152,  153,    0,  162,

      155,    0,  163,  165,  154,  156,  164,  166,  157,  158,
      167,  159,  161,  160,  155,  158,  170,  157,  160,  162,
      171,  161,  163,  165,  156,    0,  164,  166,  159,  172,
      167,  164,  173,  166,  174,  175,  170,  178,  180,  182,
      171,    0,  171,  174,  181,  167,    0,  165,  173,  172,
        0,  179,  173,  183,  174,  175,  170,  178,  180,  182,
      184,  181,  179,  186,  181,  187,  172,  179,  189,  190,
      180,  179,  175,  183,    0,  178,  182,  191,  192,  193,
      184,  194,  181,  186,    0,  187,  195,  183,  189,  190,
      197,  196,  198,  201,  187,  202,    0,  191,  192,  193,

        0,  194,  204,  192,  194,  189,  195,  190,  193,  203,
      197,  196,  198,  201,  205,  202,  191,  196,  203,  206,
      195,    0,  204,  207,  208,  198,  209,    0,    0,  203,
      210,  202,  211,    0,  205,  212,  213,  215,  207,  206,
      216,  204,  217,  207,  208,  218,  209,  205,  209,    0,
      210,  214,  211,  206,  221,  212,  213,  215,  213,  208,
      216,  214,  217,  222,  223,  218,  224,  212,    0,  210,
      225,  214,  227,  218,  221,  226,  215,  228,  229,    0,
      217,  234,  231,  222,  223,  233,  224,    0,  221,  235,
      225,    0,  227,  237,  236,  226,    0,  228,  229,  225,

      229,  234,  231,  234,  236,  233,  239,  222,  231,  235,
      226,  233,  227,  237,  236,  240,  228,  241,  237,  242,
      244,  245,  246,  247,    0,    0,  239,  249,    0,    0,
      251,    0,  255,  239,  250,  240,    0,  241,    0,  242,
      244,  245,  246,  247,  240,  247,  244,  249,  250,  245,
      251,  252,  255,  256,  250,  257,  241,  258,  251,  246,
      259,  260,  261,  242,  262,  266,  255,    0,  264,  252,
      268,  252,  265,  256,    0,  257,  266,  258,  267,  269,
      259,  260,  261,  270,  262,  266,  272,  256,  264,  271,
      268,  259,  265,  273,  257,    0,  268,  264,  267,  269,

      275,  276,  262,  270,  265,  277,  272,  278,  272,  271,
      279,  280,  267,  273,  282,  271,  270,    0,  285,  286,
      275,  276,  287,  288,    0,  277,  289,  278,  290,    0,
      279,  280,  273,  292,  282,  278,    0,  280,  285,  286,
      275,  293,  287,  288,  285,    0,  289,  294,  290,  277,
      296,  287,  295,  292,  298,  288,  290,  286,  299,  292,
      301,  293,  303,    0,  304,  289,  305,  294,  306,    0,
      296,  307,  295,  308,  298,  310,  309,  311,  299,  293,
      301,  295,  303,  296,  304,  301,  305,  312,  306,  294,
      298,  307,  313,  308,  306,  310,  309,  311,  314,  316,

      305,  318,  319,  304,    0,    0,  320,  312,  308,  307,
      309,  321,  313,  322,  323,  313,  326,  327,  314,  316,
      328,  318,  319,    0,  314,  312,  320,  330,  331,  335,
      319,  321,  332,  322,  323,    0,  326,  327,  318,  320,
      328,  334,  336,  327,  337,  339,  341,  330,  331,  335,
      322,    0,  332,  323,  343,  326,  330,  342,  332,  345,
        0,  334,  336,    0,  337,  339,  341,  335,  339,  344,
      334,  336,  346,    0,  343,  347,  351,  342,  348,  345,
      341,  337,  350,  342,  352,  354,  353,  355,  358,  344,
      361,  357,  346,  344,    0,  347,  351,  345,  348,  363,

        0,    0,  350,    0,  352,  354,  353,  355,  358,    0,
      361,  357,  346,    0,  347,  361,  348,  357,    0,  363,
      350,    0,    0,  352,  353,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "parser.l"
#line 2 "parser.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "parser.tab.h"
int lineNum=1;
#line 806 "lex.yy.c"
#line 807 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 15 "parser.l"


#line 1027 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 366 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1026 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 17 "parser.l"
{return COLON;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 18 "parser.l"
{return COMMA;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 19 "parser.l"
{return OBB;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 20 "parser.l"
{return OBE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 21 "parser.l"
{return AB;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 22 "parser.l"
{return AE;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 23 "parser.l"
{printf("\nError in line %i, only positive value is accepted\n", lineNum);
               exit(EXIT_FAILURE);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 26 "parser.l"
{ return LAST; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 27 "parser.l"
{ return ACTIVE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 29 "parser.l"
{ return GAMEID; }	
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 30 "parser.l"
{ return DRAWID; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 31 "parser.l"
{ return DRAWTIME;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 32 "parser.l"
{ return STATUS;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 33 "parser.l"
{ return DRAWBREAK;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 34 "parser.l"
{ return VISUALDRAW;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 35 "parser.l"
{ return PRICEPOINTS;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 36 "parser.l"
{ return AMOUNT;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 38 "parser.l"
{ return WINNINGNUMBERS;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 39 "parser.l"
{ return LIST;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 40 "parser.l"
{ return BONUS;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 42 "parser.l"
{return PRIZECATEGORIES;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 43 "parser.l"
{return ID;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 44 "parser.l"
{ return DIVIDENT;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 45 "parser.l"
{ return WINNERS;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 46 "parser.l"
{ return DISTRIBUTED;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 47 "parser.l"
{ return JACKPOT;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 48 "parser.l"
{ return FIXED;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 49 "parser.l"
{ return CATEGORYTYPE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 50 "parser.l"
{ return GAMETYPE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 51 "parser.l"
{ return MINIMUMDISTRIBUTED;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 54 "parser.l"
{ return WAGERSTATISTICS;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 55 "parser.l"
{ return COLUMNS;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 56 "parser.l"
{ return WAGERS;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 57 "parser.l"
{ return ADDON;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 61 "parser.l"
{return CONTENT;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 62 "parser.l"
{return TOTALPAGES;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 63 "parser.l"
{return TOTALELEMENTS;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 64 "parser.l"
{return NUMBEROFELEMENTS;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 65 "parser.l"
{return SORT;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 66 "parser.l"
{return DIRECTION;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 67 "parser.l"
{return PROPERTY;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 68 "parser.l"
{return IGNORECASE;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 69 "parser.l"
{return NULLHANDLING;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 70 "parser.l"
{return DESCENDING;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 71 "parser.l"
{return ASCENDING;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 72 "parser.l"
{return FIRST;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 73 "parser.l"
{return SIZE;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 74 "parser.l"
{return NUMBER;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 77 "parser.l"
{printf("\%s",yytext);return BOOLEAN;}
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 78 "parser.l"
{printf("\%s",yytext);return STRING;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 79 "parser.l"
{printf("\%s",yytext);return INT;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 80 "parser.l"
{printf("\%s",yytext);return REAL_NUM;}
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 81 "parser.l"
{++lineNum;} 
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 83 "parser.l"
{;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 85 "parser.l"
ECHO;
	YY_BREAK
#line 1363 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 366 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 366 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 365);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 85 "parser.l"



